{% set name = "aiida-shell" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aiida_shell-{{ version }}.tar.gz
  sha256: b4d37ecc43cd90657540cb45dbaa1f7d41c2fb1e99e8ba0966e4f5262ba2a500

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.4,<4
    - pip
  run:
    - python >={{ python_min }}
    - aiida-core >=2.6,<3.dev0,>=2.6.1
    - dill

test:
  imports:
    - aiida_shell
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://aiida.net
  summary: AiiDA plugin that makes running shell commands easy.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - sphuber
    - jan-janssen
